<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>false</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>Bubbly.Windows</AssemblyName>
    <RootNamespace>Bubbly.Windows</RootNamespace>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\baby-cat.png" />
    <Resource Include="Assets\baby-dog.png" />
    <Resource Include="Assets\bubbly-app-icon.png" />
  </ItemGroup>
</Project>
